### ISSUE TITLE
Select VQE ansatz and optimiser interactively

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-quantum#2]
Initially, we wanted the user to select ansatz and optimiser functions interactively. In @ens-lg4's experience, however, `ck benchmark` tended to select one of deployed functions at random, so he restricted workflows to only one deployed ansatz and one deployed optimiser.

While switching between them was well implemented and documented, only a few hackathon participants tried it out, which meant that we didn't get as much diversity as we were hoping for. Therefore, we should make it interactive as originally intended.

**Comment by ens-lg4** [comment]
Done
