### ISSUE TITLE
Ask the VQE user to confirm parameters for experiments

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-quantum#3]
Given that executing VQE experiments can take a long time (especially on remote devices), we should give the user an opportunity to review and accept all VQE parameters before proceeding, especially once with defaults (`--sample_number`, `--max_iterations`, `--start_param_value`, `--repetitions`). We can also implement some lightweight recommendations (e.g. to use at least 10 repetitions on simulators).

**Comment by ens-lg4** [comment]
Done
