### ISSUE TITLE
Implement experiment checkpoint mechanisms for VQE

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-quantum#4]
At the moment, all repetitions of a VQE experiment need to complete successfully for results to be recorded. This can be wasteful when experimenting on remote devices. For example, if the first failure occurs on repetition 10 out of 10, results from all the 9 successful repetitions are lost.

We should implement progressively more sophisticated mechanisms to save results from partially completed experiments and allow the user to resume them:
- [ ] Save both successful and unsuccessful repetitions. (Would adding `"ignore_return_code": "yes" to a program command's metadata be sufficient?)
- [ ] Create a checkpoint after each iteration of the classical optimiser, so that if a failure occurs e.g. on iteration 5, the optimiser can be restarted from where it got to on iteration 4.

**Comment by psyhtest** [comment]
An obvious issue with restarting a previously failed experiment is that we first need to locate it, which may be tricky due to timestamps. A number of compatible experiments may be shown to the user to select.

**Comment by ens-lg4** [comment]
A `qiskit-vqe`-specific solution that I have just implemented is a retry-loop wrapped around the quantum code that evaluates the energy.

When the client times out waiting for the server's response, the timeout exception is caught and the same quantum subroutine call is attempted again (without changing even the timeout value). This should recover us from a temporary glitch, but we still have to be careful about choosing the timeout, and also about not loosing the owner's "units" in the process.

A smarter solution could be implemented on the level of autotuning module (recovery from any kind of glitch in the program being benchmarked), but I am currently out of my depth to do it.

Please feel free to reopen if this solution is insufficient.
