### ISSUE TITLE
Create permalinks to workflows

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-quantum#8]
At the moment, we ask users to go to http://cknowledge.org/repo and then select the relevant workflow from the dropdown menu. One of the workflows is also designated as the default one. We should allow passing direct links to workflows.

**Comment by ens-lg4** [comment]
In the context of social networking they are usually called "permalinks"

**Comment by psyhtest** [comment]
Thanks @ens-lg4, that's the word I was looking for!
