### ISSUE TITLE
New filters for quantum workflows

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-quantum#9]
At the moment, we can filter by "Platform", "Team" and "Minimizer method" (can change to "Minimizer"). We should also add at least two further filters: "Ansatz" and "Molecule".

As it only makes sense to plot solutions for a single molecule at a time (e.g. either H2 or He), the "Molecule" filter cannot have the field "All".

**Comment by psyhtest** [comment]
Another level of filtering even before "Platform" could be "Vendor": Rigetti, IBM, etc. - but I'm not sure we have this in the metadata now. Can probably just display "N/A" if not found.

**Comment by psyhtest** [comment]
I'd also rename "Platform" to "Device".

**Comment by psyhtest** [comment]
For the "Solution Convergence" workflow it would be useful to filter by "Point" (but also OK for the "Time-To-Solution").

**Comment by raduetsya** [comment]
New filters will filter data by `['run']['vqe_input']['molecule']` for "Molecule" and `['run']['vqe_input']['vendor']` for "Vendor". Ansatz will be filtered by already existing `['run']['vqe_input']['ansatz_method']`.

**Comment by ens-lg4** [comment]
The new filters are now working as intended. Thanks, @raduetsya !
